In [2]:
import autokeras as ak
import tensorflow as tf
import numpy as np
import pandas as pd

In [3]:
data = pd.read_csv("../../data/processed-data/g_2010_2023_with_target.csv")
data.head()

,Date,close,open,high,low,volume,SMA_20,RSI,ATR,MACD_12_26_9,MACDh_12_26_9,MACDs_12_26_9,target
0,2010-02-22,1113.1,1122.1,1131.5,1110.0,137550.0,1094.805,53.590093,24.216037,-3.999113,9.175987,-13.175100,0
1,2010-02-23,1103.2,1114.1,1121.7,1099.6,161290.0,1095.180,49.690402,24.051662,-3.831580,7.474816,-11.306396,0
2,2010-02-24,1097.2,1103.5,1108.8,1090.2,176130.0,1095.125,47.437372,23.630803,-4.135290,5.736885,-9.872175,1
3,2010-02-25,1108.5,1096.2,1110.0,1088.5,206760.0,1096.325,51.864031,23.467253,-3.424688,5.157989,-8.582677,0
4,2010-02-26,1118.9,1108.0,1119.5,1104.6,129610.0,1098.030,55.572467,22.813155,-1.999292,5.266708,-7.266000,0

In [ ]:
from sklearn.model_selection import train_test_split


X, Y = 
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, shuffle=False)